window.TCM_DATA = {
  prescriptions: [
    {
      id: 'respiratory-cough-template',
      specialty: { zh: '呼吸系统', en: 'Respiratory' },
      disease: { zh: '咳嗽', en: 'Cough' },
      pattern: { zh: '需辨风寒、风热、痰湿、阴虚等证型', en: 'Differentiate wind-cold, wind-heat, phlegm-dampness, yin deficiency, and related patterns' },
      summary: { zh: '外感或内伤均可致咳，采集时需标注寒热虚实与痰象。', en: 'Cough may arise from external or internal patterns; record cold/heat, excess/deficiency, and phlegm signs.' },
      composition: { zh: '示例字段：君臣佐使、剂量、炮制、煎服法。', en: 'Example fields: roles, dosage, processing, decoction and administration.' },
      method: { zh: '仅记录来源用法；未审校前不输出可执行剂量。', en: 'Record source instructions only; do not provide actionable dosing before review.' },
      effect: { zh: '宣肺止咳、化痰平喘等需与证型对应。', en: 'Actions such as diffusing Lung qi, relieving cough, transforming phlegm, and calming wheeze must match the pattern.' },
      caseNote: { zh: '医案需记录年龄、症状、舌脉、疗程和复诊变化。', en: 'Case notes should include age, symptoms, tongue/pulse, course, and follow-up changes.' },
      caution: { zh: '发热喘促、咯血、儿童或孕期需及时就医。', en: 'Seek medical care for fever with dyspnea, hemoptysis, children, or pregnancy.' },
      source: { zh: '待补充授权来源/公版医籍/临床指南', en: 'Pending licensed source/public-domain classic/clinical reference' },
      reviewStatus: 'unreviewed',
      riskLevel: 'medium',
      updatedAt: '2026-05-11'
    },
    {
      id: 'digestive-epigastric-pain-template',
      specialty: { zh: '消化系统', en: 'Digestive' },
      disease: { zh: '胃脘痛', en: 'Epigastric pain' },
      pattern: { zh: '需辨寒邪客胃、肝胃不和、脾胃虚寒、瘀血阻络', en: 'Differentiate cold invading the Stomach, Liver-Stomach disharmony, Spleen-Stomach deficiency cold, and blood stasis' },
      summary: { zh: '需区分寒邪客胃、肝胃不和、脾胃虚寒、瘀血阻络等。', en: 'Differentiate cold invading the Stomach, Liver-Stomach disharmony, Spleen-Stomach deficiency cold, or blood stasis.' },
      composition: { zh: '示例字段：方名、药物组成、克数、加减与禁忌。', en: 'Example fields: formula name, ingredients, grams, modifications, contraindications.' },
      method: { zh: '采集煎煮、饭前后、疗程与加减规则；异常症状先转诊。', en: 'Collect decoction, timing, course, and modification rules; refer red flags first.' },
      effect: { zh: '温中散寒、疏肝和胃、健脾止痛等。', en: 'Warm the middle, disperse cold, soothe Liver, harmonize Stomach, strengthen Spleen, and relieve pain.' },
      caseNote: { zh: '医案需排除急腹症、消化道出血等红旗信号。', en: 'Case notes must screen red flags such as acute abdomen and gastrointestinal bleeding.' },
      caution: { zh: '剧痛、黑便、呕血、体重下降应转诊现代医学检查。', en: 'Severe pain, melena, hematemesis, or weight loss requires medical evaluation.' },
      source: { zh: '待补充授权来源/公版医籍/临床指南', en: 'Pending licensed source/public-domain classic/clinical reference' },
      reviewStatus: 'source_verified',
      riskLevel: 'high',
      updatedAt: '2026-05-11'
    },
    {
      id: 'gynecology-irregular-menstruation-template',
      specialty: { zh: '妇科', en: 'Gynecology' },
      disease: { zh: '月经不调', en: 'Irregular menstruation' },
      pattern: { zh: '需辨肝郁、血虚、血瘀、寒凝、肾虚等', en: 'Differentiate Liver constraint, blood deficiency, blood stasis, cold congealing, Kidney deficiency, and related patterns' },
      summary: { zh: '采集需标注周期、经量、色质、痛经、情志和寒热虚实。', en: 'Record cycle, volume, color/texture, pain, emotions, and cold/heat/excess/deficiency patterns.' },
      composition: { zh: '示例字段：基础方、活血/补血/温经/疏肝加减。', en: 'Example fields: base formula plus blood-moving, blood-tonifying, channel-warming, or Liver-soothing modifications.' },
      method: { zh: '记录经前、经期、经后使用阶段；先排除妊娠和异常出血。', en: 'Record premenstrual, menstrual, or postmenstrual timing; rule out pregnancy and abnormal bleeding first.' },
      effect: { zh: '调经、养血、活血、温经、疏肝。', en: 'Regulate menstruation, nourish blood, move blood, warm channels, and soothe Liver.' },
      caseNote: { zh: '医案需记录妊娠可能、内分泌检查和影像检查情况。', en: 'Case notes should record pregnancy possibility, endocrine tests, and imaging where relevant.' },
      caution: { zh: '孕期、异常出血、贫血或疑似肿瘤者不可自行用方。', en: 'Do not self-use formulas in pregnancy, abnormal bleeding, anemia, or suspected tumors.' },
      source: { zh: '待补充授权来源/公版医籍/临床指南', en: 'Pending licensed source/public-domain classic/clinical reference' },
      reviewStatus: 'safety_reviewed',
      riskLevel: 'high',
      updatedAt: '2026-05-11'
    },
    {
      id: 'pediatrics-appetite-template',
      specialty: { zh: '儿科', en: 'Pediatrics' },
      disease: { zh: '小儿食欲不振', en: 'Poor appetite in children' },
      pattern: { zh: '需辨脾胃气虚、食积、湿困、病后体虚', en: 'Differentiate Spleen-Stomach qi deficiency, food accumulation, damp obstruction, and post-illness weakness' },
      summary: { zh: '儿童处方采集必须记录年龄、体重、病程、喂养和生长发育情况。', en: 'Pediatric records must include age, weight, course, feeding, and growth/development context.' },
      composition: { zh: '示例字段：健脾、消食、化湿类药物及儿童剂量审校状态。', en: 'Example fields: Spleen-strengthening, food-dispersing, damp-transforming herbs, and pediatric dose review status.' },
      method: { zh: '儿童剂量不可从成人剂量简单折算，必须标注审校人。', en: 'Do not simply scale adult doses for children; record reviewer identity/status.' },
      effect: { zh: '健脾和胃、消食导滞。', en: 'Strengthen Spleen, harmonize Stomach, disperse food accumulation, and guide out stagnation.' },
      caseNote: { zh: '医案需排除贫血、慢性感染、内分泌和心理行为因素。', en: 'Case notes should screen anemia, chronic infection, endocrine causes, and behavioral factors.' },
      caution: { zh: '婴幼儿、体重下降、发育迟缓或持续呕吐腹泻需就医。', en: 'Infants, weight loss, developmental delay, persistent vomiting, or diarrhea require medical care.' },
      source: { zh: '待补充授权来源/公版医籍/临床指南', en: 'Pending licensed source/public-domain classic/clinical reference' },
      reviewStatus: 'unreviewed',
      riskLevel: 'high',
      updatedAt: '2026-05-11'
    },
    {
      id: 'longevity-winter-tonic-template',
      specialty: { zh: '养生长寿方', en: 'Health preservation' },
      disease: { zh: '冬季调养', en: 'Winter health preservation' },
      pattern: { zh: '需辨平和、气虚、阳虚、阴虚、痰湿等体质', en: 'Differentiate balanced, qi deficiency, yang deficiency, yin deficiency, phlegm-dampness, and related constitutions' },
      summary: { zh: '养生方不能替代疾病治疗，采集时需注明适用体质和不适用人群。', en: 'Health-preservation formulas do not replace disease care; record suitable constitutions and unsuitable populations.' },
      composition: { zh: '示例字段：补气、温阳、养血、滋阴类药食同源材料与禁忌。', en: 'Example fields: qi-tonifying, yang-warming, blood-nourishing, yin-enriching food/herb materials and contraindications.' },
      method: { zh: '记录季节、频次、饮食禁忌和停用条件。', en: 'Record season, frequency, dietary restrictions, and stop conditions.' },
      effect: { zh: '扶正固本、调和阴阳，须依据体质。', en: 'Support healthy qi, consolidate the root, and harmonize yin-yang according to constitution.' },
      caseNote: { zh: '医案需记录基础病、血压血糖、睡眠、饮食和运动。', en: 'Case notes should record comorbidities, blood pressure/glucose, sleep, diet, and exercise.' },
      caution: { zh: '感冒发热、实热、湿热、肿瘤治疗期或慢病用药者需先咨询医生。', en: 'Consult a clinician first during fever, excess heat, damp-heat, cancer treatment, or chronic medication use.' },
      source: { zh: '待补充授权来源/公版医籍/临床指南', en: 'Pending licensed source/public-domain classic/clinical reference' },
      reviewStatus: 'source_verified',
      riskLevel: 'medium',
      updatedAt: '2026-05-11'
    },
    {
      id: 'oncology-supportive-care-template',
      specialty: { zh: '肿瘤防治', en: 'Oncology supportive care' },
      disease: { zh: '肿瘤治疗期支持', en: 'Support during cancer treatment' },
      pattern: { zh: '需辨气血两虚、阴虚内热、痰瘀互结等，并结合治疗阶段', en: 'Differentiate qi-blood deficiency, yin deficiency with internal heat, phlegm-stasis binding, and treatment stage' },
      summary: { zh: '肿瘤相关处方只可作为支持性资料，必须结合肿瘤专科治疗方案。', en: 'Cancer-related formulas are supportive references only and must be coordinated with oncology care.' },
      composition: { zh: '示例字段：扶正、益气养阴、化痰散结等思路；必须标注相互作用风险。', en: 'Example fields: supporting healthy qi, benefiting qi and nourishing yin, transforming phlegm and dissipating masses; interaction risks required.' },
      method: { zh: '记录化疗/放疗/靶向/免疫治疗时间窗和停用条件。', en: 'Record chemotherapy/radiotherapy/targeted/immunotherapy timing windows and stop conditions.' },
      effect: { zh: '改善症状、扶正支持；不得宣称治愈肿瘤。', en: 'Symptom and supportive care only; never claim cancer cure.' },
      caseNote: { zh: '医案需记录分期、治疗方案、实验室指标和不良反应。', en: 'Case notes should record stage, treatment plan, labs, and adverse events.' },
      caution: { zh: '必须由肿瘤医生与中医师共同评估，避免影响抗肿瘤治疗。', en: 'Requires joint oncology and TCM review to avoid interfering with cancer treatment.' },
      source: { zh: '待补充授权来源/公版医籍/临床指南', en: 'Pending licensed source/public-domain classic/clinical reference' },
      reviewStatus: 'clinician_reviewed',
      riskLevel: 'critical',
      updatedAt: '2026-05-11'
    }
  ],
  aiProviders: [
    { name: 'Google Gemini API', free: 'Free tier with per-model RPM/TPM/RPD limits in AI Studio; limits change by model.', status: 'official-doc-required', lastVerified: '2026-05-11', url: 'https://ai.google.dev/gemini-api/docs/rate-limits' },
    { name: 'Mistral AI La Plateforme', free: 'Experiment plan is free with phone verification and restrictive rate limits; no credit card required.', status: 'official-doc-required', lastVerified: '2026-05-11', url: 'https://help.mistral.ai/en/articles/450104-how-can-i-try-the-api-for-free-with-the-experiment-plan' },
    { name: 'GroqCloud', free: 'Free developer tier with model-specific rate limits; verify current limits in console/docs.', status: 'official-doc-required', lastVerified: '2026-05-11', url: 'https://console.groq.com/docs/rate-limits' },
    { name: 'OpenRouter', free: 'Free models typically have daily and per-minute request caps; paid credits raise some caps.', status: 'official-doc-required', lastVerified: '2026-05-11', url: 'https://openrouter.ai/docs/api/reference/limits' },
    { name: 'Hugging Face Inference Providers', free: 'Includes a free tier/small credits for signed-in users across supported providers.', status: 'official-doc-required', lastVerified: '2026-05-11', url: 'https://huggingface.co/docs/hub/models-inference' },
    { name: 'NVIDIA NIM', free: 'Free development/testing access to hosted NIM APIs and self-host options for Developer Program members.', status: 'official-doc-required', lastVerified: '2026-05-11', url: 'https://www.nvidia.com/en-us/ai-data-science/products/nim-microservices/' },
    { name: 'AI21 Studio', free: '$10 trial credits for 3 months, no credit card required, then usage-based billing.', status: 'official-doc-required', lastVerified: '2026-05-11', url: 'https://www.ai21.com/pricing' },
    { name: 'Cohere', free: 'Trial keys/free trial access may be available; confirm current limits in dashboard.', status: 'official-doc-required', lastVerified: '2026-05-11', url: 'https://docs.cohere.com/' },
    { name: 'Anthropic Claude API', free: 'Generally prepaid/paid API; special research/startup/open-source credits may exist by program.', status: 'official-doc-required', lastVerified: '2026-05-11', url: 'https://support.anthropic.com/en/articles/8977456-how-do-i-pay-for-my-api-usage' },
    { name: 'OpenAI API', free: 'API usage is generally paid/prepaid; promotional credits, if any, are account/region/time limited.', status: 'official-doc-required', lastVerified: '2026-05-11', url: 'https://help.openai.com/' }
  ]
};
